import { expect, test } from "@playwright/test";
import type { APIRequestContext } from "@playwright/test";

const ACCESS_TOKEN = process.env.NEXT_PUBLIC_API_TOKEN ?? "forte-dev-token";

const resolveApiBase = () =>
  process.env.API_BASE_URL ?? process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:3000";

const generateSlug = () => `e2e-market-${Date.now()}-${Math.random().toString(16).slice(2, 8)}`;

interface MarketResponse {
  slug: string;
}

const createMarketViaApi = async (
  request: APIRequestContext,
  slug: string,
  title: string
): Promise<MarketResponse> => {
  const response = await request.post(`${resolveApiBase()}/markets`, {
    headers: {
      "x-api-token": ACCESS_TOKEN,
      "Content-Type": "application/json",
    },
    data: {
      slug,
      title,
      description: "Auto-generated by Playwright",
      state: "live",
      liquidityPool: {
        tokenSymbol: "FLOW",
        totalLiquidity: 777,
        feeBps: 42,
        providerCount: 2,
      },
      outcomes: [
        { label: "Yes", impliedProbability: 0.6, liquidity: 400 },
        { label: "No", impliedProbability: 0.4, liquidity: 377 },
      ],
    },
  });

  expect(response.status()).toBe(201);
  return response.json() as Promise<MarketResponse>;
};

test.describe("market smoke", () => {
  test.beforeEach(async ({ request }) => {
    const resetResponse = await request.post(`${resolveApiBase()}/admin/reset`);
    expect(resetResponse.status()).toBe(204);
  });

  test("creates market and displays it in list and detail views", async ({ request, page }) => {
    const slug = generateSlug();
    const title = `E2E Smoke Market ${Date.now()}`;
    const created = await createMarketViaApi(request, slug, title);
    expect(created.slug).toBe(slug);
    const marketsUrl = `/markets?ts=${Date.now()}`;

    await expect(async () => {
      const response = await request.get(`${resolveApiBase()}/markets`);
      expect(response.status()).toBe(200);
      const payload = (await response.json()) as Array<{ slug: string }>;
      expect(payload.some((market) => market.slug === slug)).toBeTruthy();
    }).toPass({ timeout: 10000 });

    await test.step("card appears in the markets list", async () => {
      await page.goto(marketsUrl, { waitUntil: "networkidle" });
      await expect(page.getByRole("heading", { name: title })).toBeVisible({ timeout: 20000 });
      await expect(
        page.locator(".market-card__status", { hasText: "Live" }).first()
      ).toBeVisible({ timeout: 20000 });
      await expect(page.getByText("777")).toBeVisible({ timeout: 20000 });
    });

    await test.step("detail page shows market data", async () => {
      await page.goto(`/markets/${slug}`, { waitUntil: "networkidle" });
      await expect(page.getByRole("heading", { name: title })).toBeVisible({ timeout: 20000 });
      await expect(page.locator(".market-detail__description")).toHaveText(
        "Auto-generated by Playwright"
      );
      await expect(
        page
          .locator(".market-detail__stats .label", { hasText: "Pool token" })
          .locator("..")
          .locator(".value")
      ).toHaveText("FLOW");
      await expect(page.locator(".outcomes-grid .outcome-card h3", { hasText: "Yes" })).toBeVisible();
      await expect(page.locator(".outcomes-grid .outcome-card h3", { hasText: "No" })).toBeVisible();
      const liquidityPanel = page.locator(".market-liquidity");
      await expect(liquidityPanel.getByRole("heading", { name: "Liquidity provider tools" })).toBeVisible();
      await expect(liquidityPanel.locator(".market-liquidity__stats")).toContainText(
        "Liquidity parameter"
      );
      await expect(liquidityPanel.getByRole("button", { name: "Pool already exists" })).toBeDisabled();
      await expect(liquidityPanel.getByRole("button", { name: "Add" })).toBeEnabled();
    });
  });

  test("quote request displays calculation in trading panel", async ({ request, page }) => {
    const slug = generateSlug();
    const title = `E2E Smoke Market ${Date.now()}`;
    await createMarketViaApi(request, slug, title);

    await page.route(`**/markets/${slug}/trade/quote`, async (route) => {
      const headers = {
        ...route.request().headers(),
        "x-api-token": ACCESS_TOKEN,
      };
      await route.continue({ headers });
    });

    await page.goto(`/markets/${slug}`);
    await expect(page.getByRole("heading", { name: "Trading" })).toBeVisible();

    const sharesInput = page.getByLabel("Shares");
    await sharesInput.fill("2");

    await page.getByRole("button", { name: "Get quote" }).click();

    const quoteGrid = page.locator(".quote-grid");
    await expect(quoteGrid).toBeVisible();
    await expect(quoteGrid.getByText("Current probability")).toBeVisible();
    await expect(quoteGrid.locator("dt", { hasText: "Flow" })).toBeVisible();
  });
});
